const PLAYER_JOINED = 'player joined'
const UPDATEGAMELIST = 'update game list'
const STARTGAME = 'start game'
const WITHDRAW_CARD = 'withdraw card'
const WELCOME = 'welcome'
const WAIT = 'wait for other players'
const UPDATE_CLIENT = 'update request client'
const UPDATE_SERVER = 'update request server'
const CARDS_MELDED = 'cards melded'
const UPDATE = 'update request'
const DISCARD_CARD = 'card discarded'
const SUCCESS = 'success'
const WIN = 'game won'
const TIE = 'game tie'
const SUCCESSFUL_MELD = 'successful meld'
const FAILED_MELD = 'failed meld'
const PICKED_MELD_CARD = 'picked meld card'
const PICKED_MELD_SUCCESS = 'picked meld success'
const CARDS_LAYOFF = 'cards layoff'
const GAME_MESSAGE = 'game message'


module.exports = { PLAYER_JOINED, UPDATEGAMELIST, STARTGAME, WITHDRAW_CARD, WELCOME, WAIT, UPDATE_CLIENT, UPDATE_SERVER, CARDS_MELDED, UPDATE , SUCCESS, DISCARD_CARD, SUCCESSFUL_MELD, FAILED_MELD, PICKED_MELD_CARD, PICKED_MELD_SUCCESS, CARDS_LAYOFF, WIN, TIE, GAME_MESSAGE  }
